/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SmartAccess.Client.OpenAPIDateConverter;

namespace SmartAccess.Model
{
    /// <summary>
    /// Defines ConsentType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ConsentType
    {
        /// <summary>
        /// Enum APPROVAL for value: CONSENT_APPROVAL
        /// </summary>
        [EnumMember(Value = "CONSENT_APPROVAL")]
        APPROVAL = 1,

        /// <summary>
        /// Enum REJECTION for value: CONSENT_REJECTION
        /// </summary>
        [EnumMember(Value = "CONSENT_REJECTION")]
        REJECTION = 2

    }

}
