/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SmartAccess.Client.OpenAPIDateConverter;

namespace SmartAccess.Model
{
    /// <summary>
    /// CreateActionTemplateDTO
    /// </summary>
    [DataContract(Name = "CreateActionTemplateDTO")]
    public partial class CreateActionTemplateDTO : IEquatable<CreateActionTemplateDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateActionTemplateDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateActionTemplateDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateActionTemplateDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="version">version.</param>
        /// <param name="serviceProviderId">serviceProviderId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="tenantName">tenantName (required).</param>
        /// <param name="systemName">systemName (required).</param>
        /// <param name="resourceTemplates">resourceTemplates (required).</param>
        /// <param name="conditionTemplates">conditionTemplates (required).</param>
        public CreateActionTemplateDTO(string id = default(string), double version = default(double), string serviceProviderId = default(string), string name = default(string), string description = default(string), string tenantName = default(string), string systemName = default(string), List<CreateResourceTemplateDTO> resourceTemplates = default(List<CreateResourceTemplateDTO>), List<CreateConditionTemplateDTO> conditionTemplates = default(List<CreateConditionTemplateDTO>))
        {
            // to ensure "serviceProviderId" is required (not null)
            if (serviceProviderId == null) {
                throw new ArgumentNullException("serviceProviderId is a required property for CreateActionTemplateDTO and cannot be null");
            }
            this.ServiceProviderId = serviceProviderId;
            // to ensure "name" is required (not null)
            if (name == null) {
                throw new ArgumentNullException("name is a required property for CreateActionTemplateDTO and cannot be null");
            }
            this.Name = name;
            // to ensure "description" is required (not null)
            if (description == null) {
                throw new ArgumentNullException("description is a required property for CreateActionTemplateDTO and cannot be null");
            }
            this.Description = description;
            // to ensure "tenantName" is required (not null)
            if (tenantName == null) {
                throw new ArgumentNullException("tenantName is a required property for CreateActionTemplateDTO and cannot be null");
            }
            this.TenantName = tenantName;
            // to ensure "systemName" is required (not null)
            if (systemName == null) {
                throw new ArgumentNullException("systemName is a required property for CreateActionTemplateDTO and cannot be null");
            }
            this.SystemName = systemName;
            // to ensure "resourceTemplates" is required (not null)
            if (resourceTemplates == null) {
                throw new ArgumentNullException("resourceTemplates is a required property for CreateActionTemplateDTO and cannot be null");
            }
            this.ResourceTemplates = resourceTemplates;
            // to ensure "conditionTemplates" is required (not null)
            if (conditionTemplates == null) {
                throw new ArgumentNullException("conditionTemplates is a required property for CreateActionTemplateDTO and cannot be null");
            }
            this.ConditionTemplates = conditionTemplates;
            this.Id = id;
            this._Version = version;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets _Version
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public double _Version { get; set; }

        /// <summary>
        /// Gets or Sets ServiceProviderId
        /// </summary>
        [DataMember(Name = "serviceProviderId", IsRequired = true, EmitDefaultValue = false)]
        public string ServiceProviderId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets TenantName
        /// </summary>
        [DataMember(Name = "tenantName", IsRequired = true, EmitDefaultValue = false)]
        public string TenantName { get; set; }

        /// <summary>
        /// Gets or Sets SystemName
        /// </summary>
        [DataMember(Name = "systemName", IsRequired = true, EmitDefaultValue = false)]
        public string SystemName { get; set; }

        /// <summary>
        /// Gets or Sets ResourceTemplates
        /// </summary>
        [DataMember(Name = "resourceTemplates", IsRequired = true, EmitDefaultValue = false)]
        public List<CreateResourceTemplateDTO> ResourceTemplates { get; set; }

        /// <summary>
        /// Gets or Sets ConditionTemplates
        /// </summary>
        [DataMember(Name = "conditionTemplates", IsRequired = true, EmitDefaultValue = false)]
        public List<CreateConditionTemplateDTO> ConditionTemplates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateActionTemplateDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  _Version: ").Append(_Version).Append("\n");
            sb.Append("  ServiceProviderId: ").Append(ServiceProviderId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  TenantName: ").Append(TenantName).Append("\n");
            sb.Append("  SystemName: ").Append(SystemName).Append("\n");
            sb.Append("  ResourceTemplates: ").Append(ResourceTemplates).Append("\n");
            sb.Append("  ConditionTemplates: ").Append(ConditionTemplates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateActionTemplateDTO);
        }

        /// <summary>
        /// Returns true if CreateActionTemplateDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateActionTemplateDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateActionTemplateDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this._Version == input._Version ||
                    this._Version.Equals(input._Version)
                ) && 
                (
                    this.ServiceProviderId == input.ServiceProviderId ||
                    (this.ServiceProviderId != null &&
                    this.ServiceProviderId.Equals(input.ServiceProviderId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.TenantName == input.TenantName ||
                    (this.TenantName != null &&
                    this.TenantName.Equals(input.TenantName))
                ) && 
                (
                    this.SystemName == input.SystemName ||
                    (this.SystemName != null &&
                    this.SystemName.Equals(input.SystemName))
                ) && 
                (
                    this.ResourceTemplates == input.ResourceTemplates ||
                    this.ResourceTemplates != null &&
                    input.ResourceTemplates != null &&
                    this.ResourceTemplates.SequenceEqual(input.ResourceTemplates)
                ) && 
                (
                    this.ConditionTemplates == input.ConditionTemplates ||
                    this.ConditionTemplates != null &&
                    input.ConditionTemplates != null &&
                    this.ConditionTemplates.SequenceEqual(input.ConditionTemplates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                hashCode = hashCode * 59 + this._Version.GetHashCode();
                if (this.ServiceProviderId != null)
                    hashCode = hashCode * 59 + this.ServiceProviderId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.TenantName != null)
                    hashCode = hashCode * 59 + this.TenantName.GetHashCode();
                if (this.SystemName != null)
                    hashCode = hashCode * 59 + this.SystemName.GetHashCode();
                if (this.ResourceTemplates != null)
                    hashCode = hashCode * 59 + this.ResourceTemplates.GetHashCode();
                if (this.ConditionTemplates != null)
                    hashCode = hashCode * 59 + this.ConditionTemplates.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
