/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ApiErrorDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiErrorDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiErrorDTO
        //private ApiErrorDTO instance;

        public ApiErrorDTOTests()
        {
            // TODO uncomment below to create an instance of ApiErrorDTO
            //instance = new ApiErrorDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiErrorDTO
        /// </summary>
        [Fact]
        public void ApiErrorDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiErrorDTO
            //Assert.IsType<ApiErrorDTO>(instance);
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
