/*
 * @ao/ah-api
 *
 * Telia Association Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ApprovalDoneUrlDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApprovalDoneUrlDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApprovalDoneUrlDTO
        //private ApprovalDoneUrlDTO instance;

        public ApprovalDoneUrlDTOTests()
        {
            // TODO uncomment below to create an instance of ApprovalDoneUrlDTO
            //instance = new ApprovalDoneUrlDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApprovalDoneUrlDTO
        /// </summary>
        [Fact]
        public void ApprovalDoneUrlDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApprovalDoneUrlDTO
            //Assert.IsType<ApprovalDoneUrlDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ApprovalDoneURL'
        /// </summary>
        [Fact]
        public void ApprovalDoneURLTest()
        {
            // TODO unit test for the property 'ApprovalDoneURL'
        }

    }

}
