/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing AuthTicketDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthTicketDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthTicketDTO
        //private AuthTicketDTO instance;

        public AuthTicketDTOTests()
        {
            // TODO uncomment below to create an instance of AuthTicketDTO
            //instance = new AuthTicketDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthTicketDTO
        /// </summary>
        [Fact]
        public void AuthTicketDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthTicketDTO
            //Assert.IsType<AuthTicketDTO>(instance);
        }


        /// <summary>
        /// Test the property 'AuthTicket'
        /// </summary>
        [Fact]
        public void AuthTicketTest()
        {
            // TODO unit test for the property 'AuthTicket'
        }

    }

}
