/*
 * @ao/ah-api
 *
 * Telia Association Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentRequestTokenBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentRequestTokenBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentRequestTokenBody
        //private ConsentRequestTokenBody instance;

        public ConsentRequestTokenBodyTests()
        {
            // TODO uncomment below to create an instance of ConsentRequestTokenBody
            //instance = new ConsentRequestTokenBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentRequestTokenBody
        /// </summary>
        [Fact]
        public void ConsentRequestTokenBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentRequestTokenBody
            //Assert.IsType<ConsentRequestTokenBody>(instance);
        }


        /// <summary>
        /// Test the property 'RequestingToken'
        /// </summary>
        [Fact]
        public void RequestingTokenTest()
        {
            // TODO unit test for the property 'RequestingToken'
        }

    }

}
