/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentRequestSearchResultDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentRequestSearchResultDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentRequestSearchResultDTO
        //private ConsentRequestSearchResultDTO instance;

        public ConsentRequestSearchResultDTOTests()
        {
            // TODO uncomment below to create an instance of ConsentRequestSearchResultDTO
            //instance = new ConsentRequestSearchResultDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentRequestSearchResultDTO
        /// </summary>
        [Fact]
        public void ConsentRequestSearchResultDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentRequestSearchResultDTO
            //Assert.IsType<ConsentRequestSearchResultDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Fact]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }
        /// <summary>
        /// Test the property 'TermsAndConditions'
        /// </summary>
        [Fact]
        public void TermsAndConditionsTest()
        {
            // TODO unit test for the property 'TermsAndConditions'
        }
        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Fact]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }
        /// <summary>
        /// Test the property 'ReqServiceProviderId'
        /// </summary>
        [Fact]
        public void ReqServiceProviderIdTest()
        {
            // TODO unit test for the property 'ReqServiceProviderId'
        }
        /// <summary>
        /// Test the property 'ReqServiceProviderName'
        /// </summary>
        [Fact]
        public void ReqServiceProviderNameTest()
        {
            // TODO unit test for the property 'ReqServiceProviderName'
        }
        /// <summary>
        /// Test the property 'ReqPrincipalId'
        /// </summary>
        [Fact]
        public void ReqPrincipalIdTest()
        {
            // TODO unit test for the property 'ReqPrincipalId'
        }
        /// <summary>
        /// Test the property 'ReqPrincipalName'
        /// </summary>
        [Fact]
        public void ReqPrincipalNameTest()
        {
            // TODO unit test for the property 'ReqPrincipalName'
        }
        /// <summary>
        /// Test the property 'ConsServiceProviderId'
        /// </summary>
        [Fact]
        public void ConsServiceProviderIdTest()
        {
            // TODO unit test for the property 'ConsServiceProviderId'
        }
        /// <summary>
        /// Test the property 'ConsServiceProviderName'
        /// </summary>
        [Fact]
        public void ConsServiceProviderNameTest()
        {
            // TODO unit test for the property 'ConsServiceProviderName'
        }
        /// <summary>
        /// Test the property 'NumApproved'
        /// </summary>
        [Fact]
        public void NumApprovedTest()
        {
            // TODO unit test for the property 'NumApproved'
        }
        /// <summary>
        /// Test the property 'NumRejected'
        /// </summary>
        [Fact]
        public void NumRejectedTest()
        {
            // TODO unit test for the property 'NumRejected'
        }
        /// <summary>
        /// Test the property 'ResponseTotalStatus'
        /// </summary>
        [Fact]
        public void ResponseTotalStatusTest()
        {
            // TODO unit test for the property 'ResponseTotalStatus'
        }
        /// <summary>
        /// Test the property 'NumAffectedUsers'
        /// </summary>
        [Fact]
        public void NumAffectedUsersTest()
        {
            // TODO unit test for the property 'NumAffectedUsers'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Consents'
        /// </summary>
        [Fact]
        public void ConsentsTest()
        {
            // TODO unit test for the property 'Consents'
        }

    }

}
