/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentRequestSearchResultDTOConsents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentRequestSearchResultDTOConsentsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentRequestSearchResultDTOConsents
        //private ConsentRequestSearchResultDTOConsents instance;

        public ConsentRequestSearchResultDTOConsentsTests()
        {
            // TODO uncomment below to create an instance of ConsentRequestSearchResultDTOConsents
            //instance = new ConsentRequestSearchResultDTOConsents();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentRequestSearchResultDTOConsents
        /// </summary>
        [Fact]
        public void ConsentRequestSearchResultDTOConsentsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentRequestSearchResultDTOConsents
            //Assert.IsType<ConsentRequestSearchResultDTOConsents>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
