/*
 * @ao/ah-api
 *
 * Telia Association Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentSummaryDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentSummaryDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentSummaryDTO
        //private ConsentSummaryDTO instance;

        public ConsentSummaryDTOTests()
        {
            // TODO uncomment below to create an instance of ConsentSummaryDTO
            //instance = new ConsentSummaryDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentSummaryDTO
        /// </summary>
        [Fact]
        public void ConsentSummaryDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentSummaryDTO
            //Assert.IsType<ConsentSummaryDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ConsPrincipalId'
        /// </summary>
        [Fact]
        public void ConsPrincipalIdTest()
        {
            // TODO unit test for the property 'ConsPrincipalId'
        }
        /// <summary>
        /// Test the property 'ConsPrincipalName'
        /// </summary>
        [Fact]
        public void ConsPrincipalNameTest()
        {
            // TODO unit test for the property 'ConsPrincipalName'
        }
        /// <summary>
        /// Test the property 'Policy'
        /// </summary>
        [Fact]
        public void PolicyTest()
        {
            // TODO unit test for the property 'Policy'
        }

    }

}
