/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentRequestFinalizeUrlDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentRequestFinalizeUrlDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentRequestFinalizeUrlDTO
        //private ConsentRequestFinalizeUrlDTO instance;

        public ConsentRequestFinalizeUrlDTOTests()
        {
            // TODO uncomment below to create an instance of ConsentRequestFinalizeUrlDTO
            //instance = new ConsentRequestFinalizeUrlDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentRequestFinalizeUrlDTO
        /// </summary>
        [Fact]
        public void ConsentRequestFinalizeUrlDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentRequestFinalizeUrlDTO
            //Assert.IsType<ConsentRequestFinalizeUrlDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ConsReqFinalizeURL'
        /// </summary>
        [Fact]
        public void ConsReqFinalizeURLTest()
        {
            // TODO unit test for the property 'ConsReqFinalizeURL'
        }

    }

}
