/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentRequestUrlDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentRequestUrlDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentRequestUrlDTO
        //private ConsentRequestUrlDTO instance;

        public ConsentRequestUrlDTOTests()
        {
            // TODO uncomment below to create an instance of ConsentRequestUrlDTO
            //instance = new ConsentRequestUrlDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentRequestUrlDTO
        /// </summary>
        [Fact]
        public void ConsentRequestUrlDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentRequestUrlDTO
            //Assert.IsType<ConsentRequestUrlDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ConsentRequestURL'
        /// </summary>
        [Fact]
        public void ConsentRequestURLTest()
        {
            // TODO unit test for the property 'ConsentRequestURL'
        }

    }

}
