/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentType
        //private ConsentType instance;

        public ConsentTypeTests()
        {
            // TODO uncomment below to create an instance of ConsentType
            //instance = new ConsentType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentType
        /// </summary>
        [Fact]
        public void ConsentTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentType
            //Assert.IsType<ConsentType>(instance);
        }



    }

}
