/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing CreateActionTemplateDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateActionTemplateDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateActionTemplateDTO
        //private CreateActionTemplateDTO instance;

        public CreateActionTemplateDTOTests()
        {
            // TODO uncomment below to create an instance of CreateActionTemplateDTO
            //instance = new CreateActionTemplateDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateActionTemplateDTO
        /// </summary>
        [Fact]
        public void CreateActionTemplateDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateActionTemplateDTO
            //Assert.IsType<CreateActionTemplateDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'ServiceProviderId'
        /// </summary>
        [Fact]
        public void ServiceProviderIdTest()
        {
            // TODO unit test for the property 'ServiceProviderId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'TenantName'
        /// </summary>
        [Fact]
        public void TenantNameTest()
        {
            // TODO unit test for the property 'TenantName'
        }
        /// <summary>
        /// Test the property 'SystemName'
        /// </summary>
        [Fact]
        public void SystemNameTest()
        {
            // TODO unit test for the property 'SystemName'
        }
        /// <summary>
        /// Test the property 'ResourceTemplates'
        /// </summary>
        [Fact]
        public void ResourceTemplatesTest()
        {
            // TODO unit test for the property 'ResourceTemplates'
        }
        /// <summary>
        /// Test the property 'ConditionTemplates'
        /// </summary>
        [Fact]
        public void ConditionTemplatesTest()
        {
            // TODO unit test for the property 'ConditionTemplates'
        }

    }

}
