/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing CreateConditionTemplateDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateConditionTemplateDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateConditionTemplateDTO
        //private CreateConditionTemplateDTO instance;

        public CreateConditionTemplateDTOTests()
        {
            // TODO uncomment below to create an instance of CreateConditionTemplateDTO
            //instance = new CreateConditionTemplateDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateConditionTemplateDTO
        /// </summary>
        [Fact]
        public void CreateConditionTemplateDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateConditionTemplateDTO
            //Assert.IsType<CreateConditionTemplateDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PolicyActionTemplateId'
        /// </summary>
        [Fact]
        public void PolicyActionTemplateIdTest()
        {
            // TODO unit test for the property 'PolicyActionTemplateId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TenantName'
        /// </summary>
        [Fact]
        public void TenantNameTest()
        {
            // TODO unit test for the property 'TenantName'
        }
        /// <summary>
        /// Test the property 'SystemName'
        /// </summary>
        [Fact]
        public void SystemNameTest()
        {
            // TODO unit test for the property 'SystemName'
        }
        /// <summary>
        /// Test the property 'ValidationType'
        /// </summary>
        [Fact]
        public void ValidationTypeTest()
        {
            // TODO unit test for the property 'ValidationType'
        }
        /// <summary>
        /// Test the property 'ValidationParams'
        /// </summary>
        [Fact]
        public void ValidationParamsTest()
        {
            // TODO unit test for the property 'ValidationParams'
        }
        /// <summary>
        /// Test the property 'Pii'
        /// </summary>
        [Fact]
        public void PiiTest()
        {
            // TODO unit test for the property 'Pii'
        }
        /// <summary>
        /// Test the property 'E2eEncrypted'
        /// </summary>
        [Fact]
        public void E2eEncryptedTest()
        {
            // TODO unit test for the property 'E2eEncrypted'
        }

    }

}
