/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing CreateResourceTemplateDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateResourceTemplateDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateResourceTemplateDTO
        //private CreateResourceTemplateDTO instance;

        public CreateResourceTemplateDTOTests()
        {
            // TODO uncomment below to create an instance of CreateResourceTemplateDTO
            //instance = new CreateResourceTemplateDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateResourceTemplateDTO
        /// </summary>
        [Fact]
        public void CreateResourceTemplateDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateResourceTemplateDTO
            //Assert.IsType<CreateResourceTemplateDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PolicyActionTemplateId'
        /// </summary>
        [Fact]
        public void PolicyActionTemplateIdTest()
        {
            // TODO unit test for the property 'PolicyActionTemplateId'
        }
        /// <summary>
        /// Test the property 'TenantName'
        /// </summary>
        [Fact]
        public void TenantNameTest()
        {
            // TODO unit test for the property 'TenantName'
        }
        /// <summary>
        /// Test the property 'SystemName'
        /// </summary>
        [Fact]
        public void SystemNameTest()
        {
            // TODO unit test for the property 'SystemName'
        }
        /// <summary>
        /// Test the property 'ResourceTagTemplates'
        /// </summary>
        [Fact]
        public void ResourceTagTemplatesTest()
        {
            // TODO unit test for the property 'ResourceTagTemplates'
        }

    }

}
