/*
 * @ao/ah-api
 *
 * Telia Association Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing DebugDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DebugDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DebugDTO
        //private DebugDTO instance;

        public DebugDTOTests()
        {
            // TODO uncomment below to create an instance of DebugDTO
            //instance = new DebugDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DebugDTO
        /// </summary>
        [Fact]
        public void DebugDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" DebugDTO
            //Assert.IsType<DebugDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ExampleKeyPair'
        /// </summary>
        [Fact]
        public void ExampleKeyPairTest()
        {
            // TODO unit test for the property 'ExampleKeyPair'
        }
        /// <summary>
        /// Test the property 'AuthTicket'
        /// </summary>
        [Fact]
        public void AuthTicketTest()
        {
            // TODO unit test for the property 'AuthTicket'
        }

    }

}
