/*
 * @ao/ah-api
 *
 * Telia Association Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing DebugDTOExampleKeyPair
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DebugDTOExampleKeyPairTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DebugDTOExampleKeyPair
        //private DebugDTOExampleKeyPair instance;

        public DebugDTOExampleKeyPairTests()
        {
            // TODO uncomment below to create an instance of DebugDTOExampleKeyPair
            //instance = new DebugDTOExampleKeyPair();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DebugDTOExampleKeyPair
        /// </summary>
        [Fact]
        public void DebugDTOExampleKeyPairInstanceTest()
        {
            // TODO uncomment below to test "IsType" DebugDTOExampleKeyPair
            //Assert.IsType<DebugDTOExampleKeyPair>(instance);
        }


        /// <summary>
        /// Test the property 'Private'
        /// </summary>
        [Fact]
        public void PrivateTest()
        {
            // TODO unit test for the property 'Private'
        }
        /// <summary>
        /// Test the property 'Public'
        /// </summary>
        [Fact]
        public void PublicTest()
        {
            // TODO unit test for the property 'Public'
        }

    }

}
