/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing SearchConsentsDTOFields
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchConsentsDTOFieldsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchConsentsDTOFields
        //private SearchConsentsDTOFields instance;

        public SearchConsentsDTOFieldsTests()
        {
            // TODO uncomment below to create an instance of SearchConsentsDTOFields
            //instance = new SearchConsentsDTOFields();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchConsentsDTOFields
        /// </summary>
        [Fact]
        public void SearchConsentsDTOFieldsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchConsentsDTOFields
            //Assert.IsType<SearchConsentsDTOFields>(instance);
        }


        /// <summary>
        /// Test the property 'ConsentRequestId'
        /// </summary>
        [Fact]
        public void ConsentRequestIdTest()
        {
            // TODO unit test for the property 'ConsentRequestId'
        }
        /// <summary>
        /// Test the property 'StopCreatedAt'
        /// </summary>
        [Fact]
        public void StopCreatedAtTest()
        {
            // TODO unit test for the property 'StopCreatedAt'
        }
        /// <summary>
        /// Test the property 'StartCreatedAt'
        /// </summary>
        [Fact]
        public void StartCreatedAtTest()
        {
            // TODO unit test for the property 'StartCreatedAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ConsServiceProviderId'
        /// </summary>
        [Fact]
        public void ConsServiceProviderIdTest()
        {
            // TODO unit test for the property 'ConsServiceProviderId'
        }
        /// <summary>
        /// Test the property 'ReqServiceProviderId'
        /// </summary>
        [Fact]
        public void ReqServiceProviderIdTest()
        {
            // TODO unit test for the property 'ReqServiceProviderId'
        }

    }

}
