/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing SearchConsentsDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchConsentsDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchConsentsDTO
        //private SearchConsentsDTO instance;

        public SearchConsentsDTOTests()
        {
            // TODO uncomment below to create an instance of SearchConsentsDTO
            //instance = new SearchConsentsDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchConsentsDTO
        /// </summary>
        [Fact]
        public void SearchConsentsDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchConsentsDTO
            //Assert.IsType<SearchConsentsDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Skip'
        /// </summary>
        [Fact]
        public void SkipTest()
        {
            // TODO unit test for the property 'Skip'
        }
        /// <summary>
        /// Test the property 'Take'
        /// </summary>
        [Fact]
        public void TakeTest()
        {
            // TODO unit test for the property 'Take'
        }
        /// <summary>
        /// Test the property 'SearchQuery'
        /// </summary>
        [Fact]
        public void SearchQueryTest()
        {
            // TODO unit test for the property 'SearchQuery'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

    }

}
