/*
 * @ao/ah-api
 *
 * Telia Association Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SmartAccess.Api;
using SmartAccess.Model;
using SmartAccess.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SmartAccess.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceProviderPatchDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceProviderPatchDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceProviderPatchDTO
        //private ServiceProviderPatchDTO instance;

        public ServiceProviderPatchDTOTests()
        {
            // TODO uncomment below to create an instance of ServiceProviderPatchDTO
            //instance = new ServiceProviderPatchDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceProviderPatchDTO
        /// </summary>
        [Fact]
        public void ServiceProviderPatchDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceProviderPatchDTO
            //Assert.IsType<ServiceProviderPatchDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IconUrl'
        /// </summary>
        [Fact]
        public void IconUrlTest()
        {
            // TODO unit test for the property 'IconUrl'
        }
        /// <summary>
        /// Test the property 'PublicKey'
        /// </summary>
        [Fact]
        public void PublicKeyTest()
        {
            // TODO unit test for the property 'PublicKey'
        }
        /// <summary>
        /// Test the property 'InitiateConsentRequestUrl'
        /// </summary>
        [Fact]
        public void InitiateConsentRequestUrlTest()
        {
            // TODO unit test for the property 'InitiateConsentRequestUrl'
        }
        /// <summary>
        /// Test the property 'FinalizeConsentRequestUrl'
        /// </summary>
        [Fact]
        public void FinalizeConsentRequestUrlTest()
        {
            // TODO unit test for the property 'FinalizeConsentRequestUrl'
        }
        /// <summary>
        /// Test the property 'InitiateConsentUrl'
        /// </summary>
        [Fact]
        public void InitiateConsentUrlTest()
        {
            // TODO unit test for the property 'InitiateConsentUrl'
        }
        /// <summary>
        /// Test the property 'FinalizeConsentUrl'
        /// </summary>
        [Fact]
        public void FinalizeConsentUrlTest()
        {
            // TODO unit test for the property 'FinalizeConsentUrl'
        }

    }

}
