/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SmartAccess.Client;
using SmartAccess.Model;

namespace SmartAccess.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActionTemplatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Deletes a action template
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns></returns>
        void DeleteActionTemplate(string actionTemplateId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Deletes a action template
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteActionTemplateWithHttpInfo(string actionTemplateId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch all action template hierarchy&#39;s on the given service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <returns>List&lt;ActionTemplateDTO&gt;</returns>
        List<ActionTemplateDTO> GetAllActionTemplatesForSP(string serviceProviderId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch all action template hierarchy&#39;s on the given service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <returns>ApiResponse of List&lt;ActionTemplateDTO&gt;</returns>
        ApiResponse<List<ActionTemplateDTO>> GetAllActionTemplatesForSPWithHttpInfo(string serviceProviderId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch the action template matching the ID
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns>ActionTemplateDTO</returns>
        ActionTemplateDTO GetOneActionTemplateById(string actionTemplateId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch the action template matching the ID
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns>ApiResponse of ActionTemplateDTO</returns>
        ApiResponse<ActionTemplateDTO> GetOneActionTemplateByIdWithHttpInfo(string actionTemplateId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new action template hierarchy on a service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ActionTemplateDTO</returns>
        ActionTemplateDTO PostActionTemplate(CreateActionTemplateDTO createActionTemplateDTO);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new action template hierarchy on a service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ApiResponse of ActionTemplateDTO</returns>
        ApiResponse<ActionTemplateDTO> PostActionTemplateWithHttpInfo(CreateActionTemplateDTO createActionTemplateDTO);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates a existing action template by replacing it with a new version
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ActionTemplateDTO</returns>
        ActionTemplateDTO UpdateActionTemplate(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates a existing action template by replacing it with a new version
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ApiResponse of ActionTemplateDTO</returns>
        ApiResponse<ActionTemplateDTO> UpdateActionTemplateWithHttpInfo(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActionTemplatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Deletes a action template
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteActionTemplateAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Deletes a action template
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteActionTemplateWithHttpInfoAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch all action template hierarchy&#39;s on the given service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ActionTemplateDTO&gt;</returns>
        System.Threading.Tasks.Task<List<ActionTemplateDTO>> GetAllActionTemplatesForSPAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch all action template hierarchy&#39;s on the given service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ActionTemplateDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ActionTemplateDTO>>> GetAllActionTemplatesForSPWithHttpInfoAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch the action template matching the ID
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionTemplateDTO</returns>
        System.Threading.Tasks.Task<ActionTemplateDTO> GetOneActionTemplateByIdAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch the action template matching the ID
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionTemplateDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ActionTemplateDTO>> GetOneActionTemplateByIdWithHttpInfoAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new action template hierarchy on a service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionTemplateDTO</returns>
        System.Threading.Tasks.Task<ActionTemplateDTO> PostActionTemplateAsync(CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new action template hierarchy on a service provider
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionTemplateDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ActionTemplateDTO>> PostActionTemplateWithHttpInfoAsync(CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates a existing action template by replacing it with a new version
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionTemplateDTO</returns>
        System.Threading.Tasks.Task<ActionTemplateDTO> UpdateActionTemplateAsync(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates a existing action template by replacing it with a new version
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionTemplateDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ActionTemplateDTO>> UpdateActionTemplateWithHttpInfoAsync(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActionTemplatesApi : IActionTemplatesApiSync, IActionTemplatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ActionTemplatesApi : IActionTemplatesApi
    {
        private SmartAccess.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionTemplatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ActionTemplatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionTemplatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ActionTemplatesApi(string basePath)
        {
            this.Configuration = SmartAccess.Client.Configuration.MergeConfigurations(
                SmartAccess.Client.GlobalConfiguration.Instance,
                new SmartAccess.Client.Configuration { BasePath = basePath }
            );
            this.Client = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SmartAccess.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionTemplatesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ActionTemplatesApi(SmartAccess.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SmartAccess.Client.Configuration.MergeConfigurations(
                SmartAccess.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SmartAccess.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActionTemplatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ActionTemplatesApi(SmartAccess.Client.ISynchronousClient client, SmartAccess.Client.IAsynchronousClient asyncClient, SmartAccess.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SmartAccess.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SmartAccess.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SmartAccess.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SmartAccess.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SmartAccess.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Deletes a action template
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns></returns>
        public void DeleteActionTemplate(string actionTemplateId)
        {
            DeleteActionTemplateWithHttpInfo(actionTemplateId);
        }

        /// <summary>
        ///  Deletes a action template
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public SmartAccess.Client.ApiResponse<Object> DeleteActionTemplateWithHttpInfo(string actionTemplateId)
        {
            // verify the required parameter 'actionTemplateId' is set
            if (actionTemplateId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'actionTemplateId' when calling ActionTemplatesApi->DeleteActionTemplate");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("actionTemplateId", SmartAccess.Client.ClientUtils.ParameterToString(actionTemplateId)); // path parameter

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/actiontemplates/{actionTemplateId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteActionTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Deletes a action template
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteActionTemplateAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteActionTemplateWithHttpInfoAsync(actionTemplateId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Deletes a action template
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<Object>> DeleteActionTemplateWithHttpInfoAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'actionTemplateId' is set
            if (actionTemplateId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'actionTemplateId' when calling ActionTemplatesApi->DeleteActionTemplate");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("actionTemplateId", SmartAccess.Client.ClientUtils.ParameterToString(actionTemplateId)); // path parameter

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/actiontemplates/{actionTemplateId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteActionTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Fetch all action template hierarchy&#39;s on the given service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <returns>List&lt;ActionTemplateDTO&gt;</returns>
        public List<ActionTemplateDTO> GetAllActionTemplatesForSP(string serviceProviderId)
        {
            SmartAccess.Client.ApiResponse<List<ActionTemplateDTO>> localVarResponse = GetAllActionTemplatesForSPWithHttpInfo(serviceProviderId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Fetch all action template hierarchy&#39;s on the given service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <returns>ApiResponse of List&lt;ActionTemplateDTO&gt;</returns>
        public SmartAccess.Client.ApiResponse<List<ActionTemplateDTO>> GetAllActionTemplatesForSPWithHttpInfo(string serviceProviderId)
        {
            // verify the required parameter 'serviceProviderId' is set
            if (serviceProviderId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderId' when calling ActionTemplatesApi->GetAllActionTemplatesForSP");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceProviderId", SmartAccess.Client.ClientUtils.ParameterToString(serviceProviderId)); // path parameter

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ActionTemplateDTO>>("/actiontemplates/serviceproviderid/{serviceProviderId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllActionTemplatesForSP", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Fetch all action template hierarchy&#39;s on the given service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ActionTemplateDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<ActionTemplateDTO>> GetAllActionTemplatesForSPAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<List<ActionTemplateDTO>> localVarResponse = await GetAllActionTemplatesForSPWithHttpInfoAsync(serviceProviderId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Fetch all action template hierarchy&#39;s on the given service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId">The service provider id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ActionTemplateDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<List<ActionTemplateDTO>>> GetAllActionTemplatesForSPWithHttpInfoAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'serviceProviderId' is set
            if (serviceProviderId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderId' when calling ActionTemplatesApi->GetAllActionTemplatesForSP");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceProviderId", SmartAccess.Client.ClientUtils.ParameterToString(serviceProviderId)); // path parameter

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ActionTemplateDTO>>("/actiontemplates/serviceproviderid/{serviceProviderId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllActionTemplatesForSP", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Fetch the action template matching the ID
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns>ActionTemplateDTO</returns>
        public ActionTemplateDTO GetOneActionTemplateById(string actionTemplateId)
        {
            SmartAccess.Client.ApiResponse<ActionTemplateDTO> localVarResponse = GetOneActionTemplateByIdWithHttpInfo(actionTemplateId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Fetch the action template matching the ID
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <returns>ApiResponse of ActionTemplateDTO</returns>
        public SmartAccess.Client.ApiResponse<ActionTemplateDTO> GetOneActionTemplateByIdWithHttpInfo(string actionTemplateId)
        {
            // verify the required parameter 'actionTemplateId' is set
            if (actionTemplateId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'actionTemplateId' when calling ActionTemplatesApi->GetOneActionTemplateById");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("actionTemplateId", SmartAccess.Client.ClientUtils.ParameterToString(actionTemplateId)); // path parameter

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ActionTemplateDTO>("/actiontemplates/id/{actionTemplateId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetOneActionTemplateById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Fetch the action template matching the ID
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionTemplateDTO</returns>
        public async System.Threading.Tasks.Task<ActionTemplateDTO> GetOneActionTemplateByIdAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<ActionTemplateDTO> localVarResponse = await GetOneActionTemplateByIdWithHttpInfoAsync(actionTemplateId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Fetch the action template matching the ID
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionTemplateDTO)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<ActionTemplateDTO>> GetOneActionTemplateByIdWithHttpInfoAsync(string actionTemplateId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'actionTemplateId' is set
            if (actionTemplateId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'actionTemplateId' when calling ActionTemplatesApi->GetOneActionTemplateById");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("actionTemplateId", SmartAccess.Client.ClientUtils.ParameterToString(actionTemplateId)); // path parameter

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ActionTemplateDTO>("/actiontemplates/id/{actionTemplateId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetOneActionTemplateById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Creates a new action template hierarchy on a service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ActionTemplateDTO</returns>
        public ActionTemplateDTO PostActionTemplate(CreateActionTemplateDTO createActionTemplateDTO)
        {
            SmartAccess.Client.ApiResponse<ActionTemplateDTO> localVarResponse = PostActionTemplateWithHttpInfo(createActionTemplateDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a new action template hierarchy on a service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ApiResponse of ActionTemplateDTO</returns>
        public SmartAccess.Client.ApiResponse<ActionTemplateDTO> PostActionTemplateWithHttpInfo(CreateActionTemplateDTO createActionTemplateDTO)
        {
            // verify the required parameter 'createActionTemplateDTO' is set
            if (createActionTemplateDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'createActionTemplateDTO' when calling ActionTemplatesApi->PostActionTemplate");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createActionTemplateDTO;

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ActionTemplateDTO>("/actiontemplates", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostActionTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Creates a new action template hierarchy on a service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionTemplateDTO</returns>
        public async System.Threading.Tasks.Task<ActionTemplateDTO> PostActionTemplateAsync(CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<ActionTemplateDTO> localVarResponse = await PostActionTemplateWithHttpInfoAsync(createActionTemplateDTO, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a new action template hierarchy on a service provider
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionTemplateDTO)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<ActionTemplateDTO>> PostActionTemplateWithHttpInfoAsync(CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'createActionTemplateDTO' is set
            if (createActionTemplateDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'createActionTemplateDTO' when calling ActionTemplatesApi->PostActionTemplate");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createActionTemplateDTO;

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ActionTemplateDTO>("/actiontemplates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostActionTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Updates a existing action template by replacing it with a new version
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ActionTemplateDTO</returns>
        public ActionTemplateDTO UpdateActionTemplate(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO)
        {
            SmartAccess.Client.ApiResponse<ActionTemplateDTO> localVarResponse = UpdateActionTemplateWithHttpInfo(actionTemplateId, createActionTemplateDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Updates a existing action template by replacing it with a new version
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <returns>ApiResponse of ActionTemplateDTO</returns>
        public SmartAccess.Client.ApiResponse<ActionTemplateDTO> UpdateActionTemplateWithHttpInfo(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO)
        {
            // verify the required parameter 'actionTemplateId' is set
            if (actionTemplateId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'actionTemplateId' when calling ActionTemplatesApi->UpdateActionTemplate");

            // verify the required parameter 'createActionTemplateDTO' is set
            if (createActionTemplateDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'createActionTemplateDTO' when calling ActionTemplatesApi->UpdateActionTemplate");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("actionTemplateId", SmartAccess.Client.ClientUtils.ParameterToString(actionTemplateId)); // path parameter
            localVarRequestOptions.Data = createActionTemplateDTO;

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<ActionTemplateDTO>("/actiontemplates/{actionTemplateId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateActionTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Updates a existing action template by replacing it with a new version
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ActionTemplateDTO</returns>
        public async System.Threading.Tasks.Task<ActionTemplateDTO> UpdateActionTemplateAsync(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<ActionTemplateDTO> localVarResponse = await UpdateActionTemplateWithHttpInfoAsync(actionTemplateId, createActionTemplateDTO, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Updates a existing action template by replacing it with a new version
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actionTemplateId">The action template id in UUID format</param>
        /// <param name="createActionTemplateDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ActionTemplateDTO)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<ActionTemplateDTO>> UpdateActionTemplateWithHttpInfoAsync(string actionTemplateId, CreateActionTemplateDTO createActionTemplateDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'actionTemplateId' is set
            if (actionTemplateId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'actionTemplateId' when calling ActionTemplatesApi->UpdateActionTemplate");

            // verify the required parameter 'createActionTemplateDTO' is set
            if (createActionTemplateDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'createActionTemplateDTO' when calling ActionTemplatesApi->UpdateActionTemplate");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("actionTemplateId", SmartAccess.Client.ClientUtils.ParameterToString(actionTemplateId)); // path parameter
            localVarRequestOptions.Data = createActionTemplateDTO;

            // authentication (jwt) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<ActionTemplateDTO>("/actiontemplates/{actionTemplateId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateActionTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
