/*
 * @ao/ah-api
 *
 * Telia Smart Access API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SmartAccess.Client;
using SmartAccess.Model;

namespace SmartAccess.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBackofficeInternalAdminApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <returns></returns>
        void DeleteConsentRequest(string consentRequestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteConsentRequestWithHttpInfo(string consentRequestId);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <returns></returns>
        void DeleteServiceProvider(string serviceProviderId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteServiceProviderWithHttpInfo(string serviceProviderId);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ConsentRequestSummaryDTO&gt;</returns>
        List<ConsentRequestSummaryDTO> GetAllConsentRequests();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ConsentRequestSummaryDTO&gt;</returns>
        ApiResponse<List<ConsentRequestSummaryDTO>> GetAllConsentRequestsWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ConsentDTO&gt;</returns>
        List<ConsentDTO> GetAllConsents();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ConsentDTO&gt;</returns>
        ApiResponse<List<ConsentDTO>> GetAllConsentsWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ServiceProviderDTO&gt;</returns>
        List<ServiceProviderDTO> GetAllServiceProviders();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ServiceProviderDTO&gt;</returns>
        ApiResponse<List<ServiceProviderDTO>> GetAllServiceProvidersWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DebugDTO</returns>
        DebugDTO GetDebug();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DebugDTO</returns>
        ApiResponse<DebugDTO> GetDebugWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <returns>ServiceProviderDTO</returns>
        ServiceProviderDTO PatchServiceProviders(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <returns>ApiResponse of ServiceProviderDTO</returns>
        ApiResponse<ServiceProviderDTO> PatchServiceProvidersWithHttpInfo(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <returns>ServiceProviderDTO</returns>
        ServiceProviderDTO PostServiceProviders(ServiceProviderDTO serviceProviderDTO);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <returns>ApiResponse of ServiceProviderDTO</returns>
        ApiResponse<ServiceProviderDTO> PostServiceProvidersWithHttpInfo(ServiceProviderDTO serviceProviderDTO);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBackofficeInternalAdminApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteConsentRequestAsync(string consentRequestId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteConsentRequestWithHttpInfoAsync(string consentRequestId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteServiceProviderAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteServiceProviderWithHttpInfoAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ConsentRequestSummaryDTO&gt;</returns>
        System.Threading.Tasks.Task<List<ConsentRequestSummaryDTO>> GetAllConsentRequestsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ConsentRequestSummaryDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ConsentRequestSummaryDTO>>> GetAllConsentRequestsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ConsentDTO&gt;</returns>
        System.Threading.Tasks.Task<List<ConsentDTO>> GetAllConsentsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ConsentDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ConsentDTO>>> GetAllConsentsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ServiceProviderDTO&gt;</returns>
        System.Threading.Tasks.Task<List<ServiceProviderDTO>> GetAllServiceProvidersAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ServiceProviderDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ServiceProviderDTO>>> GetAllServiceProvidersWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DebugDTO</returns>
        System.Threading.Tasks.Task<DebugDTO> GetDebugAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DebugDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<DebugDTO>> GetDebugWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ServiceProviderDTO</returns>
        System.Threading.Tasks.Task<ServiceProviderDTO> PatchServiceProvidersAsync(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ServiceProviderDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServiceProviderDTO>> PatchServiceProvidersWithHttpInfoAsync(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ServiceProviderDTO</returns>
        System.Threading.Tasks.Task<ServiceProviderDTO> PostServiceProvidersAsync(ServiceProviderDTO serviceProviderDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ServiceProviderDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServiceProviderDTO>> PostServiceProvidersWithHttpInfoAsync(ServiceProviderDTO serviceProviderDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBackofficeInternalAdminApi : IBackofficeInternalAdminApiSync, IBackofficeInternalAdminApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BackofficeInternalAdminApi : IBackofficeInternalAdminApi
    {
        private SmartAccess.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BackofficeInternalAdminApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BackofficeInternalAdminApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BackofficeInternalAdminApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BackofficeInternalAdminApi(string basePath)
        {
            this.Configuration = SmartAccess.Client.Configuration.MergeConfigurations(
                SmartAccess.Client.GlobalConfiguration.Instance,
                new SmartAccess.Client.Configuration { BasePath = basePath }
            );
            this.Client = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SmartAccess.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BackofficeInternalAdminApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BackofficeInternalAdminApi(SmartAccess.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SmartAccess.Client.Configuration.MergeConfigurations(
                SmartAccess.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SmartAccess.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SmartAccess.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BackofficeInternalAdminApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public BackofficeInternalAdminApi(SmartAccess.Client.ISynchronousClient client, SmartAccess.Client.IAsynchronousClient asyncClient, SmartAccess.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SmartAccess.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SmartAccess.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SmartAccess.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SmartAccess.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SmartAccess.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <returns></returns>
        public void DeleteConsentRequest(string consentRequestId)
        {
            DeleteConsentRequestWithHttpInfo(consentRequestId);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public SmartAccess.Client.ApiResponse<Object> DeleteConsentRequestWithHttpInfo(string consentRequestId)
        {
            // verify the required parameter 'consentRequestId' is set
            if (consentRequestId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'consentRequestId' when calling BackofficeInternalAdminApi->DeleteConsentRequest");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("consentRequestId", SmartAccess.Client.ClientUtils.ParameterToString(consentRequestId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/backoffice/consent_requests/{consentRequestId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteConsentRequest", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteConsentRequestAsync(string consentRequestId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteConsentRequestWithHttpInfoAsync(consentRequestId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentRequestId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<Object>> DeleteConsentRequestWithHttpInfoAsync(string consentRequestId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'consentRequestId' is set
            if (consentRequestId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'consentRequestId' when calling BackofficeInternalAdminApi->DeleteConsentRequest");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("consentRequestId", SmartAccess.Client.ClientUtils.ParameterToString(consentRequestId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/backoffice/consent_requests/{consentRequestId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteConsentRequest", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <returns></returns>
        public void DeleteServiceProvider(string serviceProviderId)
        {
            DeleteServiceProviderWithHttpInfo(serviceProviderId);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public SmartAccess.Client.ApiResponse<Object> DeleteServiceProviderWithHttpInfo(string serviceProviderId)
        {
            // verify the required parameter 'serviceProviderId' is set
            if (serviceProviderId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderId' when calling BackofficeInternalAdminApi->DeleteServiceProvider");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceProviderId", SmartAccess.Client.ClientUtils.ParameterToString(serviceProviderId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/backoffice/serviceproviders/{serviceProviderId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteServiceProvider", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteServiceProviderAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteServiceProviderWithHttpInfoAsync(serviceProviderId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<Object>> DeleteServiceProviderWithHttpInfoAsync(string serviceProviderId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'serviceProviderId' is set
            if (serviceProviderId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderId' when calling BackofficeInternalAdminApi->DeleteServiceProvider");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceProviderId", SmartAccess.Client.ClientUtils.ParameterToString(serviceProviderId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/backoffice/serviceproviders/{serviceProviderId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteServiceProvider", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ConsentRequestSummaryDTO&gt;</returns>
        public List<ConsentRequestSummaryDTO> GetAllConsentRequests()
        {
            SmartAccess.Client.ApiResponse<List<ConsentRequestSummaryDTO>> localVarResponse = GetAllConsentRequestsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ConsentRequestSummaryDTO&gt;</returns>
        public SmartAccess.Client.ApiResponse<List<ConsentRequestSummaryDTO>> GetAllConsentRequestsWithHttpInfo()
        {
            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ConsentRequestSummaryDTO>>("/backoffice/consent_requests", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllConsentRequests", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ConsentRequestSummaryDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<ConsentRequestSummaryDTO>> GetAllConsentRequestsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<List<ConsentRequestSummaryDTO>> localVarResponse = await GetAllConsentRequestsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ConsentRequestSummaryDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<List<ConsentRequestSummaryDTO>>> GetAllConsentRequestsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ConsentRequestSummaryDTO>>("/backoffice/consent_requests", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllConsentRequests", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ConsentDTO&gt;</returns>
        public List<ConsentDTO> GetAllConsents()
        {
            SmartAccess.Client.ApiResponse<List<ConsentDTO>> localVarResponse = GetAllConsentsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ConsentDTO&gt;</returns>
        public SmartAccess.Client.ApiResponse<List<ConsentDTO>> GetAllConsentsWithHttpInfo()
        {
            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ConsentDTO>>("/backoffice/consents", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllConsents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ConsentDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<ConsentDTO>> GetAllConsentsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<List<ConsentDTO>> localVarResponse = await GetAllConsentsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ConsentDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<List<ConsentDTO>>> GetAllConsentsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ConsentDTO>>("/backoffice/consents", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllConsents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ServiceProviderDTO&gt;</returns>
        public List<ServiceProviderDTO> GetAllServiceProviders()
        {
            SmartAccess.Client.ApiResponse<List<ServiceProviderDTO>> localVarResponse = GetAllServiceProvidersWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ServiceProviderDTO&gt;</returns>
        public SmartAccess.Client.ApiResponse<List<ServiceProviderDTO>> GetAllServiceProvidersWithHttpInfo()
        {
            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ServiceProviderDTO>>("/backoffice/serviceproviders", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllServiceProviders", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ServiceProviderDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<ServiceProviderDTO>> GetAllServiceProvidersAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<List<ServiceProviderDTO>> localVarResponse = await GetAllServiceProvidersWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ServiceProviderDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<List<ServiceProviderDTO>>> GetAllServiceProvidersWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ServiceProviderDTO>>("/backoffice/serviceproviders", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllServiceProviders", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DebugDTO</returns>
        public DebugDTO GetDebug()
        {
            SmartAccess.Client.ApiResponse<DebugDTO> localVarResponse = GetDebugWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DebugDTO</returns>
        public SmartAccess.Client.ApiResponse<DebugDTO> GetDebugWithHttpInfo()
        {
            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<DebugDTO>("/backoffice/debug", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDebug", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DebugDTO</returns>
        public async System.Threading.Tasks.Task<DebugDTO> GetDebugAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<DebugDTO> localVarResponse = await GetDebugWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DebugDTO)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<DebugDTO>> GetDebugWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DebugDTO>("/backoffice/debug", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDebug", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <returns>ServiceProviderDTO</returns>
        public ServiceProviderDTO PatchServiceProviders(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO)
        {
            SmartAccess.Client.ApiResponse<ServiceProviderDTO> localVarResponse = PatchServiceProvidersWithHttpInfo(serviceProviderId, serviceProviderPatchDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <returns>ApiResponse of ServiceProviderDTO</returns>
        public SmartAccess.Client.ApiResponse<ServiceProviderDTO> PatchServiceProvidersWithHttpInfo(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO)
        {
            // verify the required parameter 'serviceProviderId' is set
            if (serviceProviderId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderId' when calling BackofficeInternalAdminApi->PatchServiceProviders");

            // verify the required parameter 'serviceProviderPatchDTO' is set
            if (serviceProviderPatchDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderPatchDTO' when calling BackofficeInternalAdminApi->PatchServiceProviders");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceProviderId", SmartAccess.Client.ClientUtils.ParameterToString(serviceProviderId)); // path parameter
            localVarRequestOptions.Data = serviceProviderPatchDTO;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<ServiceProviderDTO>("/backoffice/serviceproviders/{serviceProviderId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PatchServiceProviders", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ServiceProviderDTO</returns>
        public async System.Threading.Tasks.Task<ServiceProviderDTO> PatchServiceProvidersAsync(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<ServiceProviderDTO> localVarResponse = await PatchServiceProvidersWithHttpInfoAsync(serviceProviderId, serviceProviderPatchDTO, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderId"></param>
        /// <param name="serviceProviderPatchDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ServiceProviderDTO)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<ServiceProviderDTO>> PatchServiceProvidersWithHttpInfoAsync(string serviceProviderId, ServiceProviderPatchDTO serviceProviderPatchDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'serviceProviderId' is set
            if (serviceProviderId == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderId' when calling BackofficeInternalAdminApi->PatchServiceProviders");

            // verify the required parameter 'serviceProviderPatchDTO' is set
            if (serviceProviderPatchDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderPatchDTO' when calling BackofficeInternalAdminApi->PatchServiceProviders");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceProviderId", SmartAccess.Client.ClientUtils.ParameterToString(serviceProviderId)); // path parameter
            localVarRequestOptions.Data = serviceProviderPatchDTO;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<ServiceProviderDTO>("/backoffice/serviceproviders/{serviceProviderId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PatchServiceProviders", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <returns>ServiceProviderDTO</returns>
        public ServiceProviderDTO PostServiceProviders(ServiceProviderDTO serviceProviderDTO)
        {
            SmartAccess.Client.ApiResponse<ServiceProviderDTO> localVarResponse = PostServiceProvidersWithHttpInfo(serviceProviderDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <returns>ApiResponse of ServiceProviderDTO</returns>
        public SmartAccess.Client.ApiResponse<ServiceProviderDTO> PostServiceProvidersWithHttpInfo(ServiceProviderDTO serviceProviderDTO)
        {
            // verify the required parameter 'serviceProviderDTO' is set
            if (serviceProviderDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderDTO' when calling BackofficeInternalAdminApi->PostServiceProviders");

            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = serviceProviderDTO;


            // make the HTTP request
            var localVarResponse = this.Client.Post<ServiceProviderDTO>("/backoffice/serviceproviders", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostServiceProviders", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ServiceProviderDTO</returns>
        public async System.Threading.Tasks.Task<ServiceProviderDTO> PostServiceProvidersAsync(ServiceProviderDTO serviceProviderDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            SmartAccess.Client.ApiResponse<ServiceProviderDTO> localVarResponse = await PostServiceProvidersWithHttpInfoAsync(serviceProviderDTO, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SmartAccess.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceProviderDTO"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ServiceProviderDTO)</returns>
        public async System.Threading.Tasks.Task<SmartAccess.Client.ApiResponse<ServiceProviderDTO>> PostServiceProvidersWithHttpInfoAsync(ServiceProviderDTO serviceProviderDTO, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'serviceProviderDTO' is set
            if (serviceProviderDTO == null)
                throw new SmartAccess.Client.ApiException(400, "Missing required parameter 'serviceProviderDTO' when calling BackofficeInternalAdminApi->PostServiceProviders");


            SmartAccess.Client.RequestOptions localVarRequestOptions = new SmartAccess.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = SmartAccess.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = SmartAccess.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = serviceProviderDTO;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ServiceProviderDTO>("/backoffice/serviceproviders", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostServiceProviders", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
